// <auto-generated />
using HillHigh1980.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HillHigh1980.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HillHigh1980DbContext))]
    partial class HillHigh1980DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HillHigh1980.Core.Entity.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City");

                    b.Property<int>("RosterId");

                    b.Property<string>("State");

                    b.HasKey("LocationId");

                    b.HasIndex("RosterId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("HillHigh1980.Core.Entity.Roster", b =>
                {
                    b.Property<int>("RosterId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption");

                    b.Property<string>("FirstName");

                    b.Property<string>("Image");

                    b.Property<string>("LastName");

                    b.Property<string>("Link");

                    b.Property<string>("Middle");

                    b.HasKey("RosterId");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("HillHigh1980.Core.Entity.Location", b =>
                {
                    b.HasOne("HillHigh1980.Core.Entity.Roster", "Roster")
                        .WithMany("Locations")
                        .HasForeignKey("RosterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
